### PR TITLE
Fix Types (Hoist Statics and Props Inference)

### PR DESCRIPTION
**Pull request by azizhk**
@radex This is ready now.
Fixes Props Inference and Hoists Statics.

CC: @jamieparkinson Would love if you could review also.

### CODE REVIEW

**Comment by jamieparkinson** [comment]
Ha, I no longer work with this library or even with TS/JS at all but this does look good to me. I remember not being especially happy with what I'd done at the time, and being vaguely aware that there were some holes in it, and your (very clear) explanatory comments sound familiar re the complexity that had to be captured - so I'd trust that this is a good job!

**Comment by azizhk** [comment]
> your (very clear) explanatory comments

😅  the code including comments have been taken from [react-redux](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/index.d.ts)'s types.

**Comment by radex** [comment]
@azizhk Hey! Thank you for your contribution. I wish you'd pinged me about it, because I must have missed (or forgotten) about this PR. Do you mind fixing up the conflict? I would love to merge it

**Comment by azizhk** [comment]
Can I create a new PR and get Hacktoberfest credit? 😅

**Comment by radex** [comment]
@azizhk heck yeah dude, get that t-shirt!

**Comment by azizhk** [comment]
Thanks @radex.
Closed in favor of https://github.com/Nozbe/withObservables/pull/98

**Pull request closed without merging**
